server:
  port: 8181

spring:
  application:
    name: moon-db
  datasource:
    url: jdbc:postgresql://postgres:5432/orbitals
#    url: jdbc:postgresql://localhost:5433/orbitals
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: users
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
